---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maxwell-reporting
  annotations:
    datadoghq.com/service-name: maxwell-reporting
    github.com/project-slug: vend/maxwell
spec:
  type: service
  lifecycle: production
  owner: platform
  system: maxwell
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maxwell-permissions-shard02
  annotations:
    datadoghq.com/service-name: maxwell-permissions-shard02
    github.com/project-slug: vend/maxwell
    aws.amazon.com/ecs-service-arn: arn:aws:ecs:us-west-2:542640492856:service/core-consumer-production/maxwell-permissions-shard02-production
  tags:
  - daemon
  - maxwell
spec:
  type: service
  lifecycle: production
  owner: platform
  system: maxwell
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maxwell-vend-group07
  annotations:
    datadoghq.com/service-name: maxwell-vend-group07
    github.com/project-slug: vend/maxwell
    aws.amazon.com/ecs-service-arn: arn:aws:ecs:us-west-2:542640492856:service/core-consumer-production/maxwell-vend-group07-production
  tags:
  - daemon
  - maxwell
spec:
  type: service
  lifecycle: production
  owner: platform
  system: maxwell
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maxwell-clocky
  annotations:
    datadoghq.com/service-name: maxwell-clocky
    github.com/project-slug: vend/maxwell
    aws.amazon.com/ecs-service-arn: arn:aws:ecs:us-west-2:542640492856:service/core-consumer-production/maxwell-clocky-production
  tags:
  - daemon
  - maxwell
spec:
  type: service
  lifecycle: production
  owner: platform
  system: maxwell
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maxwell-permissions-shard03
  annotations:
    datadoghq.com/service-name: maxwell-permissions-shard03
    github.com/project-slug: vend/maxwell
    aws.amazon.com/ecs-service-arn: arn:aws:ecs:us-west-2:542640492856:service/core-consumer-production/maxwell-permissions-shard03-production
  tags:
  - daemon
  - maxwell
spec:
  type: service
  lifecycle: production
  owner: platform
  system: maxwell
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maxwell-permissions-shard04
  annotations:
    datadoghq.com/service-name: maxwell-permissions-shard04
    github.com/project-slug: vend/maxwell
    aws.amazon.com/ecs-service-arn: arn:aws:ecs:us-west-2:542640492856:service/core-consumer-production/maxwell-permissions-shard04-production
  tags:
  - daemon
  - maxwell
spec:
  type: service
  lifecycle: production
  owner: platform
  system: maxwell
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maxwell-jaws
  annotations:
    datadoghq.com/service-name: maxwell-jaws
    github.com/project-slug: vend/maxwell
    aws.amazon.com/ecs-service-arn: arn:aws:ecs:us-west-2:542640492856:service/core-consumer-production/maxwell-jaws-production
  tags:
  - daemon
  - maxwell
spec:
  type: service
  lifecycle: production
  owner: platform
  system: maxwell
